# Generated by Django 3.1.6 on 2021-03-31 11:54

import ckeditor_uploader.fields
from django.db import migrations, models
import django_resized.forms
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date_published', models.DateField(auto_now_add=True)),
                ('date_created', models.DateField(auto_now=True)),
                ('author', models.CharField(default='Aremu Azeez Taiwo', max_length=200)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=0, size=[3000, 1740], upload_to='article_pics')),
                ('time_read', models.IntegerField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('slug', models.SlugField()),
                ('status', models.CharField(choices=[('Drafted', 'Drafted'), ('Published', 'Published')], default='DRAFT', max_length=20)),
                ('count_words', models.CharField(default=0, max_length=50)),
                ('read_time', models.CharField(default=0, max_length=50)),
                ('deleted', models.BooleanField(default=False)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('views', models.ManyToManyField(blank=True, to='django_blog.IpModel')),
            ],
            options={
                'verbose_name_plural': 'blogs',
                'ordering': ('-date_published',),
            },
        ),
    ]
