# Generated by Django 3.1.6 on 2021-03-31 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='time_read',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
