# Generated by Django 3.1.6 on 2021-04-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0002_auto_20210331_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
