# Generated by Django 3.1.6 on 2021-04-01 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0003_auto_20210401_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='author',
            field=models.CharField(blank=True, default='Aremu Azeez Taiwo', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='count_words',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date_created',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date_published',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='read_time',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
