# Generated by Django 3.1.6 on 2021-04-02 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0004_auto_20210401_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='clap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_clap', models.PositiveIntegerField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_blog.blogs')),
            ],
        ),
    ]
