# Generated by Django 3.1.6 on 2021-04-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0005_clap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clap',
            name='number_of_clap',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
